schema Description(AuthoritativeCustomizable):
    """
    Object containing the descriptions.

    Attributes
    ----------
    purpose : str, optional
        Intended purpose for the provided data.
    limitations : str, optional
        Technical, compliance, and legal limitations for data use.
    usage : str, optional
        Recommended usage of the data.
    """
    purpose?: str
    limitations?: str
    usage?: str

